GET http://localhost:3000/subscribers

###

get http://localhost:3000/User/all

###
DELETE http://localhost:3000/User/62077c553088650b9017640e

###
POST  http://localhost:3000/User
Content-Type: application/json

{
    "username": "dongos"
}
###

GET  http://localhost:3000/Novel
Content-Type: application/json

{
    "title": "dongos",
    "total_chapter":"something",
    "author":"something",
    "description":"hehe",
    "rating":"woaw",
    "started_year":23,
    "country":"mongolia",
    "categories":"620f8fb9ef9a0490c58480d7",
    "created_by":"620f8eb2a41fcb0493f05b65"
}

###

GET   http://localhost:3000/Category
Content-Type: application/json

{
    "title": "test"
   
}
