GET http://localhost:3000/subscribers

###

get http://localhost:3000/User/all

###
DELETE http://localhost:3000/User/62077c553088650b9017640e

###
POST  http://localhost:3000/User
Content-Type: application/json

{
    "username": "dongos"
}